<?php
/** @var $block Promo */

use Candidate\PromoWidget\Block\Promo;
$config = $block->getConfig();
if (empty($config)) {
    return;
}

?>
<?php if ($block->canShowPromo()) : ?>
    <div id="candidate-promo-widget" data-bind="text:'<?= $config['message'] ?>'"></div>

    <script type="text/x-magento-init">
        {
            "#candidate-promo-widget": {
                "Candidate_PromoWidget/js/promo-init": {
                    "config": <?= json_encode($config) ?>
        }
    }
}
    </script>
<?php endif; ?>


