<?php
/** @var $block Promo */

use Candidate\PromoWidget\Block\Promo;
$config = $block->getConfig();
if (empty($config)) {
    return;
}

?>
<div id="candidate-promo-widget"><?= $config['message'] ?></div>

<script type="text/x-magento-init">
    {
        "#candidate-promo-widget": {
            "Candidate_PromoWidget/js/promo-init": {}
        }
    }
</script>
<script>
    const element = document.getElementById('candidate-promo-widget');
    element.style.display = 'none';
    if (element) {
    // Show it after 5 seconds
        setTimeout(function () {
            element.style.display = 'block';
            console.log('Widget displayed after 5s');
        }, 5000);
    }
</script>

